#!/bin/bash

# Script pentru a lista toate variabilele de mediu necesare

echo "📋 Variabile de mediu necesare pentru Vercel:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔴 OBLIGATORII:"
echo ""
echo "1. MONGODB_URI"
echo "   - Connection string pentru MongoDB Atlas"
echo ""
echo "2. REVOLUT_SECRET_KEY"
echo "   - Secret key pentru Revolut Merchant API"
echo "   - Format: sk_..."
echo ""
echo "3. REVOLUT_WEBHOOK_SECRET"
echo "   - Signing secret pentru webhook-uri Revolut"
echo "   - Format: wsk_..."
echo "   - ✅ DEJA ADĂUGAT"
echo ""
echo "4. STRIPE_SECRET_KEY"
echo "   - Secret key pentru Stripe API"
echo "   - Format: sk_..."
echo ""
echo "5. STRIPE_WEBHOOK_SECRET"
echo "   - Signing secret pentru webhook-uri Stripe"
echo "   - Format: whsec_..."
echo ""
echo "6. RESEND_API_KEY"
echo "   - API key pentru Resend (trimite email-uri)"
echo "   - Format: re_..."
echo ""
echo "7. EMAIL_FROM"
echo "   - Email de la care se trimit email-urile"
echo "   - Format: 'Zoomout Crew <contact@zoomoutcrew.com>'"
echo ""
echo "8. NEXT_PUBLIC_BASE_URL"
echo "   - URL-ul de bază al site-ului"
echo "   - Format: https://zoomoutcrew.com"
echo ""
echo "🟡 OPȚIONALE:"
echo ""
echo "9. REVOLUT_API_URL"
echo "   - URL-ul API Revolut (default: https://merchant.revolut.com)"
echo ""
echo "10. CONTACT_EMAIL_TO"
echo "    - Email pentru contact form (default: contact@zoomoutcrew.com)"
echo ""
echo "11. FORMSPREE_FORM_ID"
echo "    - ID pentru Formspree (dacă folosești)"
echo ""
echo "12. RESEND_AUDIENCE_ID"
echo "    - Audience ID pentru newsletter (dacă folosești)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 Pentru a importa din .env.local:"
echo "   1. Deschide .env.local în editor"
echo "   2. Copiază toate variabilele (fără comentarii)"
echo "   3. În Vercel, click 'Import .env' și lipește conținutul"
echo ""
